#Set True Color
set-option -sa terminal-overrides ",xterm*:Tc"
set -s default-terminal 'tmux-256color'
#Allow mouse
set -g mouse on

#Set prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

#List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @dracula-plugins "cpu-usage git network-ping ram-usage"
set -g @dracula-show-powerline false
set -g @dracula-show-flags true
set -g @dracula-show-left-icon hostname
set -g @dracula-show-empty-plugins true

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

#Run command on new-window

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
