#Dracula Theme
import = ["~/.config/alacritty/dracula.toml"]
#Catpuccin theme
#import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
#   "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
#]

[shell]
program = "/usr/bin/zsh"
args = ["-l","-c","tmux attach || tmux"]

[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true

[cursor]
style = "Beam"

[mouse]
hide_when_typing = true
